### ISSUE TITLE
PayPal update

### ISSUE THREAD

**Issue by martonlederer** [novayadi85/paypal-SDK#1]
Hey!
Your repo stopped working, i think because of a PayPal update. Can you please update it?

**Comment by novayadi85** [comment]
Hi MartonDev...
Have you try to update your composer? 
Please get latest version on https://github.com/paypal/PayPal-PHP-SDK/releases...
and change file composer.json to latest version eq: 1.11 -> 1.12 and then update...
I've tried and work in 1.11 and 1.12, maybe you have another issue instead above? 

thanks

**Comment by martonlederer** [comment]
Thank you and sorry for being a noob... My problem is that I don't know how to use composer on cpanel and thats why it is not updating...

**Comment by novayadi85** [comment]
You can clone this repo to your local server then update composer...
Then upload the SDK by cPanel...
